### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by pedrodanielcsantos** [Doist/JobSchedulerCompat#3]
Here lies a list of possible small improvements that can be done in the lib's codebase:

- [ ] Replace usage of `@TargetApi` with the newer `@RequiresApi`;
- [ ] Update comment on `JobSchedulerJobService` as that service isn't only for `JobSchedulerSchedulerV21` but for the whole _"family"_ (V21, V24 and V26);
- [ ] Detail a bit further the documentation on `JobService` like, for instance explain better the logic of the custom binder in the scope of that class and its workflow;
- [ ] Improve the comment on `Scheduler`;
- [ ] Add some brief comments about the logic/restrictions of the parameters "conversion" and on some of the _"magic values"_ on `GcmScheduler` (an example of the usefulness of comments related to both these scenarios can be seen around `PARAM_TRIGGER_WINDOW_END`'s logic);
- [ ] A class-level comment on `GcmIntentParser` explaining briefly its purpose/logic/workflow;-
- [ ] Change the order of the methods o  `AlarmScheduler` so that it matches super's order (`getTag()` should be _after_ `onJobCompleted`);

**Comment by goncalossilva** [comment]
Hi Pedro! Thanks a lot for these. :blush: I have addressed these.

A couple of comments:
> Replace usage of `@TargetApi` with the newer `@RequiresApi`;

Despite the overlap, these annotations don't serve the same exact purpose. TargetApi is a lint-oriented annotation (and what makes the most sense when used internally in the library), while RequiresApi is a dev-oriented annotation (eg. great to lock functions or classes to a certain API for external developers). There are a couple of `@RequiresApi` in the codebase for this case, but for other cases I feel like `@TargetApi` is still the correct annotation.

> Add some brief comments about the logic/restrictions of the parameters "conversion" and on some of the _"magic values"_ on `GcmScheduler` (an example of the usefulness of comments related to both these scenarios can be seen around `PARAM_TRIGGER_WINDOW_END`'s logic);

I've added a few relevant links instead, on which the whole code is based from (namely, GcmNetworkManager's documentation and Firebase JobDispatcher's source code). Reading those should make the flow clear.

I've also commented on the obscure variables. :sweat_smile:
