### ISSUE TITLE
Why we need to use this library rather than WorkManager?

### ISSUE THREAD

**Issue by dnkilic** [Doist/JobSchedulerCompat#8]
I just want to learn more about the functionality provided by JobSchedulerCompat. What is the difference between Android WorkManager and this library?

**Comment by goncalossilva** [comment]
In theory, you don't. JobSchedulerCompat was built before WorkManager existed, and their purpose is very similar. The design goals differ though. I'll list a few of the key differences:
* JobSchedulerCompat is designed in a way that makes it trivial to swap out with JobScheduler itself. If one day you stop supporting APIs below 21, all you need to do is update the import statements and you're good to go. WorkManager uses a different API that ties you into WorkManager itself.
* Behind the scenes, both rely on JobScheduler and AlarmManager, although JobSchedulerCompat:
  * Still uses JobScheduler for APIs 21 and 22 (WorkManager uses AlarmManager for those)
  * Uses GcmNetworkManager for APIs below 21 when Google Play Services is available (WorkManager uses AlarmManager for those)
* WorkManager supports APIs 14 and up. JobSchedulerCompat supports APIs 16 and up.
* WorkManager is built and maintained by Google. JobSchedulerCompat is built and maintained by Doist.

Hope that helps. Feel free to ask any specific questions you might have.
